### ISSUE TITLE
OAM framework library needed

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/spec#242]
Now we have OAM specification and implementation on K8s, but we still need some OAM framework libraries for OAM to be widely promoted and applied. 

Some common features for this framework could be:

1. **Validation and Parsing for OAM yaml files**: this could be done by a common admission controller [we have discussed in Rudr](https://github.com/oam-dev/rudr/issues/349).
2. **Distinguish different workload and execute**: this framework could give an entrance for OAM App Config and then distinguish different workload( including 6 standard workload and some popular extensions such as K8s deployment), give interface for them to convert into different resources for different platforms.
3. **Component and Traits orchestration**: orchestration wasn't defined in OAM spec, but every implementation will need it.
4. **Application Scope**: I have implemented health scope in Rudr, things like scope instance creation, overlap validation, component joining can be included in this framework.

This framework maybe also need to be written in different languages, first choice is Golang I think.

We are designing this framework, hope we can discuss deeply in this issue.

\cc @hongchaodeng @resouer

**Comment by resouer** [comment]
@vturecek Some early stage experiments we are doing:

For 2: interfaces and scaffold code to help workloads implementation easier, thus platform engineers just fill in "translation logic" instead of creating everything from zero.

For 3: scaffold code for _ApplicationConfiguration_ controller, with pre-defined interfaces for well-known steps (e.g. initialize components, apply traits etc), thus platform engineers could "plug-in" their own logic to control of these steps in fine grained manner.

btw, @wonderflow 's description maybe misleading since they are use cases the framework/sdk could help, not "features" of it. The only features are scaffold code and interfaces for building blocks of OAM implementation.

Sounds good?

**Comment by KaiwenWang** [comment]
Second feature is strong expected by  me which is  a third party runtime management frame provider and multi cloud service provider.

**Comment by wonderflow** [comment]
Closing as we already have such frameworks:

[Recommended] For OAM v1alpha2 https://github.com/crossplane/oam-kubernetes-runtime

For OAM v1alpha1 https://github.com/oam-dev/oam-go-sdk
