### ISSUE TITLE
Proposal: OAM for CRD + Operator, make workload have more extension ability like trait 

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/spec#272]
Now we could clearly understand Component and Trait, they both have extensions. The extension for OAM in K8s world is obviously using CRD+Operator. 

We could define any CRD+Operator as a Trait by using json schema. However, we can't do the same thing for Workload.

Trait has properties which allow us to define json schema.  While we can only define key-value pairs for workload.That is why some users complain we are not friendly to extended workload. 

So I propose we could let `Workload Types` use jsonschema to define like trait. Then, we could extend those existing CRD+Operators (eg. OpenFaaS) more easily into `Workload Types`.

On the other hand, we should change [the type of workloadsettings](https://github.com/oam-dev/spec/blob/master/3.component_model.md#spec) to be [`Properties`](https://github.com/oam-dev/spec/blob/master/6.application_configuration.md#properties).

What's more, we could have a OAM registry in the future. Users could register their CRD to this registry, if the CRD is a kind of workload, they will get an automatically generated `Workload`; if the  CRD is a kind of operator trait, they will get an automatically generated `Trait`.

\cc @resouer @hongchaodeng

**Comment by wonderflow** [comment]
what about your ideas? @technosophos @vturecek

**Comment by vturecek** [comment]
This is closely related to #268. My response there was basically that the core workload type concept might be too closely tied to containers, when there are other workloads (like processes) that could be supported by those core workload types.

Using a JSON schema properties object instead of the current workloadSettings is a step in the right direction, but I think we may also need to explore decoupling core workload types from the container spec. 

For example, could I define an extended workload type (like processes) that can be used with the core workload types (server, worker, task)?

**Comment by wonderflow** [comment]
> For example, could I define an extended workload type (like processes) that can be used with the core workload types (server, worker, task)?

What if let the workloadsettings be also used by core workload type?

**Comment by hongchaodeng** [comment]
Per https://github.com/oam-dev/spec/issues/281#issuecomment-565271085,
Let's close this and converge discussion to https://github.com/oam-dev/spec/issues/281
