### ISSUE TITLE
Proposal: OAM for CRD + Operator, Trait should have Group/Version/Kind defined in Trait Spec

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/spec#279]
We hope we could write CRD+Operator for Trait, related with #272 

Now we could define trait schema using jsonschema in `properties`, the missing part is we should add  Group/Version/Kind definition into the Trait, using some field like `type`.

If we don't have a G/V/K in trait, we can't register a CRD+Operator as a Trait.

**Comment by hi-wayne** [comment]
This is a good idea, which could achieve separate k8s controllers for trait and workload (even scope). We can further consider, when oam achieving, make the full use of k8s crd to exchange/event watch the information (between trait and workload or scop and workload) rather than grpc api. We will not worry about heavy use of all in one engine(one controller) with more and more workload and trait supported by oam.

**Comment by zkcrescent** [comment]
+1,  scope is probably the same

**Comment by hongchaodeng** [comment]
This has been discussed in https://github.com/oam-dev/spec/pull/44#issuecomment-521772248.

We ended up with convention over configuration.

@vturecek for the decision.

**Comment by wonderflow** [comment]
I read all the discussion in that issue, I think these fields could be optional, but still necessary to add.

My case is when we have cooperation with 3rd party Workload and 3rd party Trait, how we could find which kind of the 3rd party Trait is?  I think one of the OAM's main value is to make 
 cooperation easily.

**Comment by wonderflow** [comment]
Since OAM v1alpha2 is released, we already have G/V/K contained in trait, closing
